In [2]:
#read the data 

import numpy as np
import pandas as pd 
import os 
import ast 

data = pd.read_csv(r"datasets\fingerprint_datasets\tox21.csv")
#check the data
#data['fingerprints']=data['fingerprints'].apply(ast.literal_eval)


In [3]:
data['Y'].sum()

309.0

In [7]:
finger_prints = np.stack(data['fingerprints'].values)
print(finger_prints.shape)


(7265, 2048)


In [6]:
len(data['fingerprints'][0])

2048

In [3]:
import numpy as np
import pandas as pd
import ast

# Example DataFrame with string representation of lists
data = {
    'string_lists': ['[1, 2, 3]', '[4, 5, 6]', '[7, 8, 9]']
}
df = pd.DataFrame(data)

# Convert string representations to actual lists
df['lists'] = df['string_lists'].apply(ast.literal_eval)

# Convert the 'lists' column (now containing actual lists) to a numpy array
numpy_array = np.stack(df['lists'].values)

print(numpy_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
